#!/bin/bash
# This is my modifications of original script, which was done by Anachron. All thanks goes to him.
# Original can be found here: https://github.com/Anachron/i3blocks/tree/master/blocks
# Script is based on API: http://openweathermap.org/current
# to find your city id see 'city.list.json.gz',
# which can be downloaded here: http://bulk.openweathermap.org/sample/

API_KEY="xxxxxxxxxxxx" # your openweathermap private key goes here

# Check on http://openweathermap.org/find
CITY_ID="${BLOCK_INSTANCE}"

URGENT_LOWER=0
URGENT_HIGHER=30

ICON_SUNNY=""
ICON_CLOUDY=""
ICON_RAINY=""
ICON_STORM=""
ICON_SNOW=""
ICON_FOG=""

SYMBOL_CELSIUS="℃"

#WEATHER_URL="http://api.openweathermap.org/data/2.5/weather?id=${CITY_ID}&appid=${API_KEY}&units=metric"
WEATHER_URL="http://api.openweathermap.org/data/2.5/group?id=${CITY_ID}&APPID=${API_KEY}&units=metric"

WEATHER_INFO=$(wget -qO- "${WEATHER_URL}")
WEATHER_LOCAT=$(echo "${WEATHER_INFO}" |  grep -o -e '\"name\":\"[a-z A-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_MAIN=$(echo "${WEATHER_INFO}" | grep -o -e '\"main\":\"[a-Z]*\"' | awk -F ':' '{print $2}' | tr -d '"')
#WEATHER_DESC=$(echo "${WEATHER_INFO}" | grep -o -e '\"description\":\"[a-Z \s]*\"' | awk -F ':' '{print $2}' | tr -d '"')
#WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_TEMP=$(echo "${WEATHER_INFO}" | grep -o -e '\"temp\":\-\?[0-9]*\.\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_HUMID=$(echo "${WEATHER_INFO}" | grep -o -e '\"humidity\":[0-9]*\.\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_PRESS=$(echo "${WEATHER_INFO}" | grep -o -e '\"pressure\":[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_WND_SPD=$(echo "${WEATHER_INFO}" | grep -o -e '\"speed\":[0-9]*\.\?[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_WND_DEG=$(echo "${WEATHER_INFO}" | grep -o -e '\"deg\":[0-9]*' | awk -F ':' '{print $2}' | tr -d '"')
WEATHER_WND="wind(${WEATHER_WND_SPD}m/s, ${WEATHER_WND_DEG}°)"
ICON=""

if [[ "${WEATHER_MAIN}" = *Snow* ]]; then
  ICON=${ICON_SNOW}
elif [[ "${WEATHER_MAIN}" = *Rain* ]] || [[ "${WEATHER_MAIN}" = *Drizzle* ]]; then
  ICON=${ICON_RAINY}
elif [[ "${WEATHER_MAIN}" = *Cloud* ]]; then
  ICON=${ICON_CLOUDY}
elif [[ "${WEATHER_MAIN}" = *Clear* ]]; then
  ICON=${ICON_SUNNY}
elif [[ "${WEATHER_MAIN}" = *Fog* ]] || [[ "${WEATHER_MAIN}" = *Mist* ]]; then
  ICON=${ICON_FOG}
fi

echo "${WEATHER_LOCAT} ${WEATHER_MAIN}(${ICON}) ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${WEATHER_HUMID}% ${WEATHER_PRESS}hpa ${WEATHER_WND}"
echo "${WEATHER_LOCAT} ${WEATHER_MAIN}(${ICON}) ${WEATHER_TEMP}${SYMBOL_CELSIUS} ${WEATHER_HUMID}% ${WEATHER_PRESS}hpa ${WEATHER_WND}"
echo ""


